name: email-http-service CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ vars.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ vars.EMAIL_PASSWORD }}

    steps:
      - name: Checkout code ðŸ›Žï¸
        uses: actions/checkout@v4

      - name: Debug environment variables ðŸ•µï¸
        run: |
          echo "EMAIL_USER: $EMAIL_USER"
          echo "EMAIL_PASSWORD: [REDACTED]"

      - name: Install pnpm ðŸ“¦
        run: npm install -g pnpm

      - name: Install dependencies ðŸ§©
        run: pnpm install

      - name: Set up environment variables ðŸ“
        run: |
          echo "EMAIL_USER=$EMAIL_USER" >> .env.test
          echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> .env.test

      - name: Run tests ðŸ§ª
        run: pnpm run test:once
        env:
          NODE_ENV: test

      - name: Deploy ðŸš€
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
          echo "ðŸš€ Deployed to: $deploy_url"