on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest ğŸ§
    steps:
      - uses: actions/checkout@v3 ğŸ“¦
      - name: Install pnpm ğŸ“²
        run: npm install -g pnpm
      - name: Install dependencies âš™ï¸
        run: pnpm install
      - name: Deploy ğŸš€
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
          echo "ğŸš€ Deployed to: $deploy_url" ğŸ“„